version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
jobs:
  build_and_test:
    working_directory: ~/pinafore
    docker:
      - image: circleci/ruby:2.5-buster-node
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: pinafore
          POSTGRES_PASSWORD: pinafore
          POSTGRES_DB: pinafore_development
          BROWSER: chrome:headless
      - image: circleci/redis:5-alpine
    steps:
      - checkout
      - restore_cache:
          name: restore yarn cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install --immutable
      - run:
          name: install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y ffmpeg libicu-dev libidn11-dev libprotobuf-dev postgresql-contrib protobuf-compiler
      - run:
          name: clone mastodon
          command: yarn clone-mastodon
      - restore_cache:
          name: restore bundler cache
          key: bundler-{{ checksum "mastodon/Gemfile.lock" }}
#      - run:
#          name: lint
#          command: yarn lint
#      - run:
#          name: unit tests
#          command: yarn test-unit
      - run:
          name: wait for postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for postgres && exit 1
      - run:
          name: wait for redis to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 6379 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for redis && exit 1
#      - run:
#          name: setup database
#          command: psql -h 127.0.0.1 -d template1 -U postgres -c "CREATE USER pinafore WITH PASSWORD 'pinafore' CREATEDB;"
      - run:
          name: integration tests
          command: yarn test
      - save_cache:
          name: save yarn cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: save bundler cache
          key: bundler-{{ checksum "mastodon/Gemfile.lock" }}
          paths:
            - mastodon/vendor/bundle
